version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    environment:
      - POSTGRES_HOST=172.18.0.2
      - POSTGRES_PORT=5432
      - POSTGRES_DB=crudb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000

  frontend:
    build:
      context: ./frontend
    ports:
      - 8080:8080

  db:
    image: postgres
    environment:
      - POSTGRES_DB=crudb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
