version: '3'

services:
  backend:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=crudb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000

  frontend:
    build:
      context: .
    ports:
      - 8080:8080

  db:
    image: postgres
    environment:
      - POSTGRES_DB=crudb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
