# Utilisez l'image de base Python pour Django
FROM python:3.9

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez le fichier requirements.txt et installez les dépendances
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copiez le reste du code source dans le conteneur
COPY . .

# Exposez le port sur lequel votre application Django écoute
EXPOSE 8000

# Commande par défaut pour exécuter votre application Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
